[[languages.cpp.environments]]
CXX = "g++"
CXXFLAGS = ["-std=c++23", "-O2", "-Werror", "-Wall", "-Wextra", "-g", "-fsanitize=undefined,address"]

[[languages.cpp.environments]]
CXX = "clang++"
CXXFLAGS = ["-std=c++23", "-O2", "-Werror", "-Wall", "-Wextra", "-g", "-fsanitize=undefined,address"]
